stages:
  - build
  - package

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

variables:
  # this doesnt work yet, using link instead
  SCRIBE_VERSION: v0.0.7
  
build_helper:
  extends: .go-cache
  stage: build
  variables: 
    CGO_ENABLED: "0"
  image:
    name: golang:1.19.0-alpine
    entrypoint: [""]
  script:
    go build -o ./bin/gitlab-runner-helper apps/gitlab-runner-helper
  artifacts:
    paths:
      - bin/gitlab-runner-helper

build_runner:
  extends: .go-cache
  stage: build
  variables: 
    CGO_ENABLED: "0"
  image:
    name: golang:1.19.0-alpine
    entrypoint: [""]
  script:
    go build -o ./bin/gitlab-runner .
  artifacts:
    paths:
      - bin/gitlab-runner

runner_helper:
  stage: package
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/dockerfiles/runner-helper/Dockerfile.ubuntu"
      --destination "${CI_REGISTRY_IMAGE}/runner-helper:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG

runner:
  stage: package
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/dockerfiles/runner/ubuntu/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/runner-helper:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG