stages:
  - runner_helper
  - build

variables:
  SCRIBE_VERSION: v0.0.7
  
runner_helper:
  stage: runner_helper
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/dockerfiles/runner-helper/Dockerfile.ubuntu"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

# build-and-push-runner:
#   variables:
#     KO_DOCKER_REPO: ${CI_REGISTRY}/${CI_REGISTRY_IMAGE}
#   stage: build
#   image:
#     name: registry.gitlab.com/testifysec/docker-images/ko:0.11.2
#     entrypoint: [""]
#   script:
#     - ko auth login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
#     - ko publish --bare --tags=${CI_COMMIT_SHORT_SHA} ./cmd/archivist
  
# build-and-push-client:
#   variables:
#     KO_DOCKER_REPO: registry.gitlab.com/testifysec/judge-platform/archivist/archivistctl
#   stage: build
#   image:
#     name: registry.gitlab.com/testifysec/docker-images/ko:0.11.2
#     entrypoint: [""]
#   script:
#     - ko auth login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
#     - ko publish --bare --tags ${CI_COMMIT_SHORT_SHA} ./cmd/archivistctl


# build-and-push-helper:
