defaultBaseImage: registry.gitlab.com/testifysec/gitlab-runner/base-image:v0.1.4
baseImageOverrides:
   gitlab.com/gitlab-org/gitlab-runner/apps/gitlab-runner-helper: registry.gitlab.com/testifysec/gitlab-runner/helper-base:latest
builds:
- id: witness-gitlab-runner
  dir: .
  main: ./
  ldflags:
  - -s -w
- id: witness-gitlab-runner-helper
  dir: .
  main: apps/gitlab-runner-helper
  ldflags:
  - -s -w